# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnantgirl',
            name='mapped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
