# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160212_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntenatalVist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField()),
                ('services', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresetMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=160)),
            ],
        ),
        migrations.AddField(
            model_name='pregnantgirl',
            name='contact_number',
            field=models.CharField(default=b'', max_length=13),
        ),
        migrations.AddField(
            model_name='pregnantgirl',
            name='contact_type',
            field=models.CharField(choices=[(b'Parent', b'Parent'), (b'Guardian', b'Guardian'), (b'Spouse', b'Spouse'), (b'Sibling', b'Sibling')], default=b'Parent', max_length=20),
        ),
        migrations.AddField(
            model_name='pregnantgirl',
            name='emergency_contact',
            field=models.CharField(default=b'', max_length=32),
        ),
        migrations.AddField(
            model_name='antenatalvist',
            name='girl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PregnantGirl'),
        ),
    ]
