---
- apt: name=git state=present update_cache=yes

- apt: name={{ item }} state=present
  with_items:
    - python-pip
    - python-dev
    - libtiff5-dev
    - libjpeg8-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.6-dev
    - tk8.6-dev
    - python-tk

- pip: name={{ item }}
  with_items:
    - virtualenv

- file: path=/srv/checkout owner=www-data mode=0755 state=directory

- file: path=/srv/checkout/{{name}} owner=www-data mode=0755 state=directory

- file: path=/.ssh owner=root  mode=0755 state=directory

- user: name=root group=root

- name: send key to remote deploy user
  copy: src=keys/id_rsa_app dest=/.ssh/priv_key mode=0600

- name: checkout from bitbucket
  git: repo=git@bitbucket.org:assekalala/remzak-django.git dest=/srv/checkout/{{name}} key_file=/.ssh/priv_key accept_hostkey=true

- pip: requirements=/srv/checkout/{{name}}/requirements.txt virtualenv=/srv/checkout/{{name}}venv

- command: /srv/checkout/{{name}}venv/bin/python manage.py syncdb --noinput
  args:
    chdir: /srv/checkout/{{name}}

- command: /srv/checkout/{{name}}venv/bin/python manage.py migrate
  args:
    chdir: /srv/checkout/{{name}}

- command: /srv/checkout/{{name}}venv/bin/python manage.py collectstatic --noinput
  args:
    chdir: /srv/checkout/{{name}}




